# Generated by Django 2.2.6 on 2019-11-20 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploader', '0007_auto_20191120_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileFile',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='uploader.Device')),
                ('file_uri', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
    ]
