# Generated by Django 2.2.6 on 2019-11-22 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileFile',
        ),
    ]
