# Generated by Django 2.2.6 on 2019-11-22 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileFile',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Device')),
                ('file_uri', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_uri', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('file_type', models.CharField(max_length=1)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Device')),
            ],
        ),
    ]
