# Generated by Django 2.2.6 on 2020-01-14 19:30

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileCreationRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateTimeField()),
                ('parsed_event_files', models.FileField(upload_to=core.models.ProfileCreationRun.generate_file_path)),
                ('unlock_data', models.FileField(upload_to=core.models.ProfileCreationRun.generate_file_path)),
                ('checkpoint_data', models.FileField(upload_to=core.models.ProfileCreationRun.generate_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_file', models.FileField(upload_to=core.models.ProfileInfo.generate_profile_path)),
                ('profile_type', models.CharField(max_length=20)),
                ('used_class_samples', models.IntegerField()),
                ('score', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('fscore', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Device')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ProfileCreationRun')),
            ],
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to=core.models.DataFileInfo.generate_data_path)),
                ('start_date', models.DateTimeField()),
                ('file_type', models.CharField(max_length=1)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Device')),
            ],
        ),
    ]
