# Generated by Django 2.2.6 on 2020-01-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='file_type',
            field=models.CharField(max_length=20),
        ),
    ]
