# Generated by Django 2.2.6 on 2020-01-07 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCreationRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateTimeField()),
                ('unlock_set_uri', models.DateTimeField()),
                ('unlock_data_uri', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='profilefile',
            old_name='file_uri',
            new_name='profile_file_uri',
        ),
        migrations.RemoveField(
            model_name='profilefile',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='profilefile',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ProfileCreationRun'),
            preserve_default=False,
        ),
    ]
