# Generated by Django 2.0 on 2020-01-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecreationrun',
            name='is_64bit',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
