# Generated by Django 2.2.6 on 2020-01-08 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200107_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefile',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Device'),
        ),
        migrations.AddField(
            model_name='profilefile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
