# Generated by Django 2.2.6 on 2020-01-14 20:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200114_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafileinfo',
            name='file_type',
            field=models.CharField(choices=[(core.models.DataFileInfo.DataFileType('Event'), 'Event'), (core.models.DataFileInfo.DataFileType('Sensor'), 'Sensor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='profile_type',
            field=models.CharField(choices=[(core.models.ProfileInfo.ProfileType('Unlock'), 'Unlock'), (core.models.ProfileInfo.ProfileType('Continuous'), 'Continuous')], max_length=20),
        ),
    ]
