# Generated by Django 2.2.6 on 2020-01-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200108_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilecreationrun',
            old_name='unlock_set_uri',
            new_name='parsed_unlock_files_uri',
        ),
    ]
