# Generated by Django 2.2.6 on 2020-01-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200108_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilecreationrun',
            old_name='parsed_unlock_files_uri',
            new_name='checkpoint_data_uri',
        ),
        migrations.AddField(
            model_name='profilecreationrun',
            name='parsed_event_files_uri',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
