# Generated by Django 2.2.6 on 2020-01-15 10:33

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200115_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinfo',
            name='profile_file',
        ),
        migrations.CreateModel(
            name='ProfileFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.FileField(upload_to=core.models.ProfileInfo.generate_profile_path)),
                ('profile_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.ProfileInfo')),
            ],
        ),
    ]
