# Generated by Django 2.2.6 on 2020-01-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200109_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecreationrun',
            name='checkpoint_data_uri',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profilecreationrun',
            name='parsed_event_files_uri',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profilecreationrun',
            name='unlock_data_uri',
            field=models.CharField(max_length=200),
        ),
    ]
