# Generated by Django 2.2.6 on 2020-01-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200109_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefile',
            name='profile_type',
            field=models.CharField(default='UNLOCK', max_length=20),
            preserve_default=False,
        ),
    ]
