# Generated by Django 2.2.6 on 2020-01-15 10:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200115_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='profile_file',
            field=models.FileField(upload_to=core.models.ProfileInfo.generate_profile_path),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProfileFile',
        ),
    ]
