# Generated by Django 2.2.6 on 2020-01-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200115_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
