# Generated by Django 2.2.6 on 2020-01-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profilefile_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefile',
            name='used_class_samples',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
