# Generated by Django 2.2.6 on 2020-01-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profilefile_used_class_samples'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefile',
            name='fscore',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilefile',
            name='precision',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilefile',
            name='recall',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
