# Generated by Django 2.2.6 on 2020-01-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profileinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='android_id',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
