# Generated by Django 2.2.6 on 2020-01-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200112_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefile',
            name='score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
