# Generated by Django 2.2.6 on 2019-10-27 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='device_id',
        ),
        migrations.AddField(
            model_name='datafile',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uploader.Device'),
            preserve_default=False,
        ),
    ]
