# Generated by Django 2.2.6 on 2019-10-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_auto_20191027_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
