# Generated by Django 2.2.6 on 2019-11-19 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_auto_20191027_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='end_date',
        ),
    ]
