# Generated by Django 2.2.6 on 2019-11-22 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_delete_profilefile'),
        ('uploader', '0007_auto_20191120_0031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataFile',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
